# Generated by Django 5.0.6 on 2026-05-21 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSubscriptionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField()),
                ('telegram_chat_id', models.CharField(max_length=120)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdminChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('text', models.TextField()),
                ('direction', models.CharField(choices=[('in', 'От пользователя'), ('out', 'От администратора')], max_length=8)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform', models.CharField(blank=True, max_length=80)),
                ('cause', models.CharField(blank=True, max_length=255)),
                ('pnfl', models.CharField(db_index=True, max_length=32)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('position', models.CharField(blank=True, max_length=180)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=180)),
                ('passport', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('station', models.CharField(blank=True, max_length=180)),
                ('lang', models.CharField(default='ru', max_length=8)),
                ('generated_login', models.CharField(blank=True, max_length=150)),
                ('generated_password', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('done', 'Сделано'), ('blocked', 'Заблокирована')], default='new', max_length=16)),
                ('hrm_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
