# Generated by Django 5.0.6 on 2026-05-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_base_url', models.URLField(default='http://127.0.0.1:8000')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255)),
                ('telegram_api_key', models.CharField(blank=True, max_length=255)),
                ('telegram_webhook_url', models.URLField(blank=True)),
                ('mobile_app_name', models.CharField(default='E-NAKL Mobile', max_length=120)),
                ('mobile_api_key', models.CharField(blank=True, max_length=255)),
                ('mobile_app_base_url', models.URLField(blank=True)),
                ('mobile_app_enabled', models.BooleanField(default=True)),
                ('hrm_base_url', models.URLField(blank=True)),
                ('hrm_client_id', models.CharField(blank=True, max_length=180)),
                ('hrm_secret', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API configuration',
                'verbose_name_plural': 'API configuration',
            },
        ),
    ]
