# Generated by Django 5.0.6 on 2026-05-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchatmessage',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('video_note', 'Round video'), ('location', 'Location')], default='text', max_length=24),
        ),
        migrations.AddField(
            model_name='adminchatmessage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adminchatmessage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adminchatmessage',
            name='media',
            field=models.FileField(blank=True, upload_to='chat_uploads/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='adminchatmessage',
            name='media_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adminchatmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
