# Generated by Django 5.0.6 on 2026-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminchatmessage_kind_adminchatmessage_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfiguration',
            name='hrm_public_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='hrm_secret_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='hrm_verify_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
