# Generated by Django 5.0.6 on 2026-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakerequest',
            name='department',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
