# Generated by Django 5.0.6 on 2026-05-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_webplatform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webplatform',
            name='code',
        ),
        migrations.AddField(
            model_name='webplatform',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
