# Generated by Django 5.2.14 on 2026-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_webplatformfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='webplatform',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webplatform',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
