# Generated by Django 5.2.14 on 2026-05-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_webplatform_duration_minutes_webplatform_usage_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webplatform',
            name='duration_minutes',
        ),
    ]
