# Generated by Django 5.2.14 on 2026-05-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_webplatform_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchatmessage',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('voice', 'Voice'), ('video_note', 'Round video'), ('location', 'Location')], default='text', max_length=24),
        ),
    ]
