# Generated by Django 5.2.14 on 2026-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_internalchat_internalchatmessage_internalcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tags',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
