# Generated by Django 5.2.14 on 2026-05-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_adminchatthread_adminchatmessage_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchatthread',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=16),
        ),
    ]
