# Generated by Django 5.0.6 on 2026-06-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_fill_automatic_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterole',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='core.branch'),
        ),
        migrations.AddField(
            model_name='siterole',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='core.organization'),
        ),
    ]
