# Generated by Django 5.0.6 on 2026-06-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_siterole_branch_siterole_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterole',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='siterole',
            name='organization',
        ),
    ]
