# Generated by Django 5.0.6 on 2026-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_securitythrottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_positions',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='core.position'),
        ),
    ]
