# Generated by Django 5.0.6 on 2026-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_userprofile_allowed_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='positions_access_configured',
            field=models.BooleanField(default=False),
        ),
    ]
