# Generated by Django 5.0.6 on 2026-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_userprofile_positions_access_configured'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchatmessage',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='adminchatthread',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
