TEXTS = {
    "ru": {
        "choose_language": "Выберите язык:",
        "language_saved": "Язык выбран: Русский.",
        "welcome": "Главное меню",
        "need_subscription": "Вы ещё не подписаны на все обязательные каналы/группы.",
        "check_subscription": "Проверить подписку",
        "subscription_ok": "Подписка подтверждена.",
        "menu_new_request": "Отправить заявку",
        "menu_account": "Аккаунт",
        "menu_history": "История заявок",
        "menu_pending": "Заявки в ожидании",
        "menu_chat_admin": "Чат с администратором",
        "menu_settings": "Настройки",
        "menu_developers": "Разработчики",
        "history_empty": "История заявок пуста.",
        "account_not_found": "Данные аккаунта не найдены.",
        "pending_empty": "Заявок в ожидании нет.",
        "settings_text": "Выберите язык:",
        "developers_text": "MTU FORUM. Разработчики: MTU-1 Raqamlashtirish.",
        "web_app_text": "Откройте WEB APP: {url}",
        "send_pnfl": "Введите ваш ПНФЛ (14 цифр).\nПодсказка на фото.",
        "pnfl_invalid": "ПНФЛ должен состоять из 14 цифр. Введите ваш ПНФЛ (14 цифр).",
        "send_phone": "Введите телефон или нажмите кнопку «Поделиться контактом».\nПодсказка: +998-XX-XXX-XX-XX.",
        "phone_invalid": "Телефон должен быть в формате Узбекистана. Подсказка: +998-XX-XXX-XX-XX.",
        "share_contact": "Поделиться контактом",
        "send_passport": "Введите паспортные данные.\nПодсказка: AB1234567.",
        "passport_invalid": "Паспорт должен быть в формате AB1234567: 2 латинские буквы и 7 цифр.",
        "send_station": "Выберите предприятие.",
        "send_position": "Выберите должность.",
        "send_cause": "Опишите причину обращения.",
        "send_platform": "Выберите платформу.",
        "sent": "Ваша заявка принята. Администратор обработает ее в ближайшее время.",
        "submit_error": "Сервисе проблема с ПНФЛ (Не нашел сотрудника). Попробуйте позже. Или обратитесь в отдел кадров (Приказ, Перевод, и т.д.).",
        "admin_chat": "Напишите сообщение администратору.",
        "message_sent": "Сообщение отправлено администратору.",
    },
    "uz": {
        "choose_language": "Tilni tanlang:",
        "language_saved": "Til tanlandi: O'zbekcha.",
        "welcome": "Asosiy menyu",
        "need_subscription": "Siz hali barcha majburiy kanal/guruhlarga obuna bo'lmagansiz.",
        "check_subscription": "Obunani tekshirish",
        "subscription_ok": "Obuna tasdiqlandi.",
        "menu_new_request": "Ariza yuborish",
        "menu_account": "Akkaunt",
        "menu_history": "Arizalar tarixi",
        "menu_pending": "Kutilayotgan arizalar",
        "menu_chat_admin": "Administrator bilan chat",
        "menu_settings": "Sozlamalar",
        "menu_developers": "Dasturchilar",
        "history_empty": "Arizalar tarixi bo'sh.",
        "account_not_found": "Akkaunt ma'lumotlari topilmadi.",
        "pending_empty": "Kutilayotgan arizalar yo'q.",
        "settings_text": "Tilni tanlang:",
        "developers_text": "MTU FORUM. Dasturchilar: MTU-1 Raqamlashtirish.",
        "web_app_text": "WEB APP ni oching: {url}",
        "send_pnfl": "JSHSHIR (PINFL) raqamingizni kiriting (14 ta raqam).\nKo'rsatma rasmda.",
        "pnfl_invalid": "JSHSHIR (PINFL) 14 ta raqamdan iborat bo'lishi kerak.",
        "send_phone": "Telefon raqamingizni kiriting yoki «Kontaktni ulashish» tugmasini bosing.\nNamuna: +998-XX-XXX-XX-XX.",
        "phone_invalid": "Telefon raqami O'zbekiston formatida bo'lishi kerak. Namuna: +998-XX-XXX-XX-XX.",
        "share_contact": "Kontaktni ulashish",
        "send_passport": "Pasport ma'lumotlarini kiriting.\nNamuna: AB1234567.",
        "passport_invalid": "Pasport AB1234567 formatida bo'lishi kerak: 2 ta lotin harfi va 7 ta raqam.",
        "send_station": "Korxonani tanlang.",
        "send_position": "Lavozimni tanlang.",
        "send_cause": "Murojaat sababini yozing.",
        "send_platform": "Platformani tanlang.",
        "sent": "Arizangiz qabul qilindi. Administrator yaqin vaqt ichida ko'rib chiqadi.",
        "submit_error": "JSHSHIR (PINFL) bo'yicha muammo: xodim topilmadi. Keyinroq urinib ko'ring yoki kadrlar bo'limiga murojaat qiling (buyruq, o'tkazish va h.k.).",
        "admin_chat": "Administratorga xabar yozing.",
        "message_sent": "Xabar administratorga yuborildi.",
    },
    "uz-cyrl": {
        "choose_language": "Тилни танланг:",
        "language_saved": "Тил танланди: Ўзбекча.",
        "welcome": "Асосий меню",
        "need_subscription": "Сиз ҳали барча мажбурий канал/гуруҳларга обуна бўлмагансиз.",
        "check_subscription": "Обунани текшириш",
        "subscription_ok": "Обуна тасдиқланди.",
        "menu_new_request": "Ариза юбориш",
        "menu_account": "Аккаунт",
        "menu_history": "Аризалар тарихи",
        "menu_pending": "Кутилаётган аризалар",
        "menu_chat_admin": "Администратор билан чат",
        "menu_settings": "Созламалар",
        "menu_developers": "Дастурчилар",
        "history_empty": "Аризалар тарихи бўш.",
        "account_not_found": "Аккаунт маълумотлари топилмади.",
        "pending_empty": "Кутилаётган аризалар йўқ.",
        "settings_text": "Тилни танланг:",
        "developers_text": "MTU FORUM. Дастурчилар: MTU-1 Raqamlashtirish.",
        "web_app_text": "WEB APP ни очинг: {url}",
        "send_pnfl": "ЖШШИР (ПИНФЛ) рақамингизни киритинг (14 та рақам).\nКўрсатма расмда.",
        "pnfl_invalid": "ЖШШИР (ПИНФЛ) 14 та рақамдан иборат бўлиши керак.",
        "send_phone": "Телефон рақамингизни киритинг ёки «Контактни улашиш» тугмасини босинг.\nНамуна: +998-XX-XXX-XX-XX.",
        "phone_invalid": "Телефон рақами Ўзбекистон форматида бўлиши керак. Намуна: +998-XX-XXX-XX-XX.",
        "share_contact": "Контактни улашиш",
        "send_passport": "Паспорт маълумотларини киритинг.\nНамуна: AB1234567.",
        "passport_invalid": "Паспорт AB1234567 форматида бўлиши керак: 2 та лотин ҳарфи ва 7 та рақам.",
        "send_station": "Корхонани танланг.",
        "send_position": "Лавозимни танланг.",
        "send_cause": "Мурожаат сабабини ёзинг.",
        "send_platform": "Платформани танланг.",
        "sent": "Аризангиз қабул қилинди. Администратор яқин вақт ичида кўриб чиқади.",
        "submit_error": "ЖШШИР (ПИНФЛ) бўйича муаммо: ходим топилмади. Кейинроқ уриниб кўринг ёки кадрлар бўлимига мурожаат қилинг (буйруқ, ўтказиш ва ҳ.к.).",
        "admin_chat": "Администраторга хабар ёзинг.",
        "message_sent": "Хабар администраторга юборилди.",
    },
    "en": {
        "choose_language": "Choose language:",
        "language_saved": "Language selected: English.",
        "welcome": "Main menu",
        "need_subscription": "You are not subscribed to all required channels/groups yet.",
        "check_subscription": "Check subscription",
        "subscription_ok": "Subscription confirmed.",
        "menu_new_request": "Submit request",
        "menu_account": "Account",
        "menu_history": "Request history",
        "menu_pending": "Pending requests",
        "menu_chat_admin": "Chat with administrator",
        "menu_settings": "Settings",
        "menu_developers": "Developers",
        "history_empty": "Request history is empty.",
        "account_not_found": "Account data was not found.",
        "pending_empty": "There are no pending requests.",
        "settings_text": "Choose language:",
        "developers_text": "MTU FORUM. Developers: MTU-1 Raqamlashtirish.",
        "web_app_text": "Open WEB APP: {url}",
        "send_pnfl": "Enter your PINFL (14 digits).\nSee the photo hint.",
        "pnfl_invalid": "PINFL must contain exactly 14 digits. Enter your PINFL (14 digits).",
        "send_phone": "Enter your phone number or press Share contact.\nHint: +998-XX-XXX-XX-XX.",
        "phone_invalid": "Phone number must be in Uzbekistan format. Hint: +998-XX-XXX-XX-XX.",
        "share_contact": "Share contact",
        "send_passport": "Enter passport data.\nHint: AB1234567.",
        "passport_invalid": "Passport must match AB1234567: 2 Latin letters and 7 digits.",
        "send_station": "Select company.",
        "send_position": "Select position.",
        "send_cause": "Describe the request reason.",
        "send_platform": "Select platform.",
        "sent": "Your request has been accepted. The administrator will process it shortly.",
        "submit_error": "There is a PINFL service problem: employee was not found. Try again later or contact HR (order, transfer, etc.).",
        "admin_chat": "Write a message to administrator.",
        "message_sent": "Message sent to administrator.",
    },
}

EXTRA_TEXTS = {
    "ru": {
        "back": "Назад",
        "new_chat": "Новый чат",
        "close_chat": "Завершить чат",
        "select_chat": "Выберите чат или создайте новый.",
        "chat_opened": "Чат открыт. Напишите сообщение администратору.",
        "chat_closed": "Чат завершён.",
        "account_title": "Аккаунт",
        "no_account": "Данные аккаунта пока не найдены.",
        "history_title": "История заявок",
        "pending_title": "Заявки в ожидании",
        "no_history": "Заявок пока нет.",
        "no_pending": "Заявок в ожидании нет.",
    },
    "uz": {
        "back": "Orqaga",
        "new_chat": "Yangi chat",
        "close_chat": "Chatni yakunlash",
        "select_chat": "Chatni tanlang yoki yangisini yarating.",
        "chat_opened": "Chat ochildi. Administratorga xabar yozing.",
        "chat_closed": "Chat yakunlandi.",
        "account_title": "Akkaunt",
        "no_account": "Akkaunt ma'lumotlari hali topilmadi.",
        "history_title": "Arizalar tarixi",
        "pending_title": "Kutilayotgan arizalar",
        "no_history": "Hali arizalar yo'q.",
        "no_pending": "Kutilayotgan arizalar yo'q.",
    },
    "uz-cyrl": {
        "back": "Ортга",
        "new_chat": "Янги чат",
        "close_chat": "Чатни якунлаш",
        "select_chat": "Чатни танланг ёки янгисини яратинг.",
        "chat_opened": "Чат очилди. Администраторга хабар ёзинг.",
        "chat_closed": "Чат якунланди.",
        "account_title": "Аккаунт",
        "no_account": "Аккаунт маълумотлари ҳали топилмади.",
        "history_title": "Аризалар тарихи",
        "pending_title": "Кутилаётган аризалар",
        "no_history": "Ҳали аризалар йўқ.",
        "no_pending": "Кутилаётган аризалар йўқ.",
    },
    "en": {
        "back": "Back",
        "new_chat": "New chat",
        "close_chat": "Close chat",
        "select_chat": "Choose a chat or create a new one.",
        "chat_opened": "Chat is open. Write a message to administrator.",
        "chat_closed": "Chat closed.",
        "account_title": "Account",
        "no_account": "Account data was not found yet.",
        "history_title": "Request history",
        "pending_title": "Pending requests",
        "no_history": "No requests yet.",
        "no_pending": "No pending requests.",
    },
}


EXTRA_TEXTS["ru"].update({
    "send_full_name": "Введите Ф.И.О полностью.",
    "full_name_invalid": "Введите Ф.И.О полностью, например: Иванов Иван Иванович.",
})

EXTRA_TEXTS["uz"].update({
    "send_full_name": "F.I.O. ni to'liq kiriting.",
    "full_name_invalid": "F.I.O. ni to'liq kiriting, masalan: Ivanov Ivan Ivanovich.",
})

EXTRA_TEXTS["uz-cyrl"].update({
    "send_full_name": "Ф.И.О.ни тўлиқ киритинг.",
    "full_name_invalid": "Ф.И.О.ни тўлиқ киритинг, масалан: Иванов Иван Иванович.",
})

EXTRA_TEXTS["en"].update({
    "send_full_name": "Enter your full name.",
    "full_name_invalid": "Enter your full name, for example: Ivanov Ivan Ivanovich.",
})


def t(lang, key):
    return EXTRA_TEXTS.get(lang, EXTRA_TEXTS["ru"]).get(key) or TEXTS.get(lang, TEXTS["ru"]).get(key, TEXTS["ru"].get(key, key))
